- name: Discord Webhook Notify
  uses: rjstone/discord-webhook-notify@v1.0.4
    if: success()
    with:
        severity: info
        details: Test Succeeded!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
- name: Discord Webhook Notify
  uses: rjstone/discord-webhook-notify@v1.0.4
    if: failure()
    with:
        severity: error
        details: Test Failed!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
- name: Discord Webhook Notify
  uses: rjstone/discord-webhook-notify@v1.0.4
    if: cancelled()
    with:
        severity: warn
        details: Test Cancelled!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}